# Generated by Django 5.2.6 on 2025-09-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('door_count', models.SmallIntegerField()),
                ('roof_type', models.CharField(max_length=50)),
                ('year', models.SmallIntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
            ],
        ),
    ]
