# Generated by Django 5.2.6 on 2025-09-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='roof_type',
            field=models.CharField(choices=[('convertible', 'Convertible'), ('hardtop', 'Hardtop'), ('sunroof', 'Sunroof')], default='hardtop', max_length=50),
        ),
    ]
