# Generated by Django 5.2.6 on 2025-09-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0004_alter_car_roof_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='roof_type',
            field=models.CharField(choices=[('select roof type', 'Select Roof Type'), ('convertible', 'Convertible'), ('hardtop', 'Hardtop'), ('sunroof', 'Sunroof')], default='select roof type', max_length=50),
        ),
    ]
