# Generated by Django 5.2.6 on 2025-09-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_alter_car_roof_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('select fuel type', 'Select Fuel Type'), ('gas', 'Gas'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('lp_gas', 'LP Gas')], default='select fuel type', max_length=50),
        ),
    ]
