# Generated by Django 5.2.6 on 2025-09-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0006_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('', 'Select Fuel Type'), ('gas', 'Gas'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('lp_gas', 'LP Gas')], default='select fuel type', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='roof_type',
            field=models.CharField(choices=[('', 'Select Roof Type'), ('convertible', 'Convertible'), ('hardtop', 'Hardtop'), ('sunroof', 'Sunroof')], default='select roof type', max_length=50),
        ),
    ]
