# Generated by Django 5.2.6 on 2025-09-28 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0008_alter_car_fuel_type_alter_car_roof_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='post_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
