# Generated by Django 5.2.6 on 2025-09-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_author', models.CharField(max_length=100)),
                ('post_body', models.TextField()),
                ('post_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
