# Generated by Django 5.2.6 on 2025-09-18 00:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_author', models.CharField(max_length=100)),
                ('post_body', models.TextField()),
                ('post_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
